---

- hosts: all
  vars:
    pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_master }}"
    pdns_rec_config:
      allow-from: "198.51.100.0/24"
  roles:
    - { role: pdns_recursor-ansible }

#
# - hosts: all
#   roles:
#     - { role: pdns_recursor-ansible }
