---
- block:
    - name: Ensure the override directory exists
      file:
        path: '/etc/systemd/system/{{ pdns_rec_service_name }}.service.d'
        state: directory
        owner: root
        group: root
    - name: Create override for the service
      template:
        dest: '/etc/systemd/system/{{ pdns_rec_service_name }}.service.d/override.conf'
        src: 'override.systemd.conf.j2'
        owner: root
        group: root
      notify: Reload systemd and restart PowerDNS Recursor
  when: pdns_rec_service_overrides != {}
