---

scenario:
  name: pdns-rec-53

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: oraclelinux-8
    image: ghcr.io/oracle/oraclelinux:8
    dockerfile_tpl: centos-systemd

  - name: oraclelinux-9
    image: oraclelinux:9
    dockerfile_tpl: centos-systemd

  - name: ubuntu-2204
    image: mpaivabarbosa/molecule-systemd-ubuntu:22.04
    dockerfile_tpl: ubuntu-systemd

  - name: ubuntu-2404
    image: mpaivabarbosa/molecule-systemd-ubuntu:24.04
    dockerfile_tpl: ubuntu-systemd

  - name: debian-11
    image: mpaivabarbosa/molecule-systemd-debian:11
    dockerfile_tpl: debian-python3

  - name: debian-12
    image: mpaivabarbosa/molecule-systemd-debian:12
    dockerfile_tpl: debian-python3

  - name: rockylinux-8
    image: mpaivabarbosa/molecule-systemd-rockylinux:8
    dockerfile_tpl: centos-systemd

  - name: almalinux-8
    image: mpaivabarbosa/molecule-systemd-almalinux:8
    dockerfile_tpl: centos-systemd

  - name: rockylinux-9
    image: mpaivabarbosa/molecule-systemd-rockylinux:9
    dockerfile_tpl: centos-systemd

  - name: almalinux-9
    image: mpaivabarbosa/molecule-systemd-almalinux:9
    dockerfile_tpl: centos-systemd

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  config_options:
    defaults:
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: .ansible_cache
      fact_caching_timeout: 7200
    ssh_connection:
      pipelining: true
  inventory:
    links:
      host_vars: ../resources/host_vars/
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml
  lint: ansible-lint -x ANSIBLE0006 ANSIBLE0016

lint: yamllint vars tasks defaults meta

verifier:
  name: testinfra
  options:
    vvv: True
  directory: ../resources/tests/all
  additional_files_or_dirs:
    - ../repo-53/
    - ../systemd-overrides
