ancestor: 1.8.0
releases:
  2.0.0:
    changes:
      breaking_changes:
      - minimum supported Ansible version is 2.15 (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      - the variable pdns_rec_service_overrides now allows overriding any section
        in the service unit definition (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      bugfixes:
      - fixed Molecule DNS resolution tests by ensuring the dnspython library is installed
        on hosts (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      major_changes:
      - added support for Recursor 5.1.x, 5.2.x, and 5.3.x (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      - added support for the arm64 architecture when installing the Recursor via
        the role (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      - added tests for Debian Trixie and Enterprise Linux 10 (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      - improved YAML-based configuration for the Recursor (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      - migrated the role to use handlers to restart processes and services on changes
        (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      - switched Debian-based platforms to deb822-style APT repositories (requires
        Ansible >= 2.15). Inspired by @l00d3r in https://github.com/PowerDNS/pdns_recursor-ansible/pull/213
        and @lpmhouben in https://github.com/PowerDNS/pdns_recursor-ansible/pull/218
        (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      - updated Molecule test configuration files to YAML (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      minor_changes:
      - added the ability to mask the service. Useful for multi-instance Recursor
        deployments (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
      removed_features:
      - removed variables pdns_rec_custom_config, pdns_rec_config_from_files, and
        pdns_rec_config_from_files_dir_mode (https://github.com/PowerDNS/pdns_recursor-ansible/pull/234).
    fragments:
    - 234-upgrade-to-20.yaml
    release_date: '2026-01-16'
  2.1.0:
    changes:
      breaking_changes:
      - Ubuntu 20.04 has been removed from molecule test scenarios (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - "the Debian repository setup now exclusively uses ``ansible.builtin.deb822_repository``
        \u2014 the legacy ``apt_key``/``apt_repository`` fallback for Ubuntu < 22.04
        has been removed. This requires ``python3-debian`` on target hosts and Ansible
        >= 2.15 (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245)."
      - the ``apt_repo`` and ``gpg_key_id`` keys are no longer used in custom repository
        definitions; use ``apt_version`` and ``gpg_key`` instead (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - the ``powerdns-recursor.sources.j2`` template has been removed (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      bugfixes:
      - fix ``recursor.conf.j2`` template to coerce ``AnsibleVaultEncryptedUnicode``
        values to plain strings before type-normalisation, allowing ``!vault`` encrypted
        values to be used directly inside configuration dicts (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - fix typo in debug symbols package variable name ``default_pdns_recorsor_debug_symbols_package_name``
        to ``default_pdns_rec_debug_symbols_package_name`` in Archlinux, Debian, and
        Other vars files (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      doc_changes:
      - document ``pdns_rec_package_state``, ``pdns_rec_bin_name``, and ``pdns_rec_service_overrides``
        variables in the README (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - "fix YAML boolean conventions in README examples (``True``/``False`` \u2192
        ``true``/``false``) (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245)."
      - update README with PowerDNS Recursor 5.4.x repository installation example
        (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - update custom repository example to reflect deb822 migration (removed ``apt_repo``
        and ``gpg_key_id``, added ``apt_version``) (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      major_changes:
      - add type-normalizing Jinja2 macro to ``recursor.conf.j2`` that automatically
        converts stringified integers, floats, booleans, and lists to their native
        YAML types when rendering the configuration (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      minor_changes:
      - add ``pdns_rec_package_state`` variable to allow controlling the desired state
        of the PowerDNS Recursor packages (present, latest, or absent) (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - add support for PowerDNS Recursor 5.4.x repository including repo definition,
        molecule test scenario, and CI integration. (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - normalize ``ansible_architecture`` to lowercase when mapping to APT architecture
        names to handle inconsistent facts (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
      - use Ansible Vault for the webservice ``api_key`` in molecule test variables
        to verify that vaulted values are correctly decrypted and rendered into the
        configuration file (https://github.com/PowerDNS/pdns_recursor-ansible/pull/245).
    fragments:
    - add-rec-54-support-and-fixes.yaml
    release_date: '2026-02-23'
