ancestor: 1.8.0
add_plugin_period: true
add_contributor_section: true
changelog_filename_template: ../CHANGELOG.md
changelog_filename_version_depth: 0
changelog_nice_yaml: false
changelog_sort: alphanumerical
changes_file: changelog.yaml
changes_format: combined
ignore_other_fragment_extensions: true
is_other_project: true
keep_fragments: false
mention_ancestor: true
new_plugins_after_name: removed_features
notesdir: fragments
output_formats:
- md
prelude_section_name: release_summary
prelude_section_title: Release Summary
sanitize_changelog: true
sections:
- - major_changes
  - Major Changes
- - minor_changes
  - Minor Changes
- - breaking_changes
  - Breaking Changes / Porting Guide
- - deprecated_features
  - Deprecated Features
- - removed_features
  - Removed Features (previously deprecated)
- - security_fixes
  - Security Fixes
- - bugfixes
  - Bugfixes
- - known_issues
  - Known Issues

title: PowerDNS Recursor Ansible Role
trivial_section_name: trivial
use_fqcn: true
use_semantic_versioning: true
