---

- name: Prepare the Molecule Test Resources
  hosts: all
  #become: true
  tasks:
    # Install rsyslog to capture the PowerDNS Recursor log messages
    # when the service is not managed by systemd
    - name: Install rsyslog
      when: ansible_service_mgr != 'systemd'
      block:
        - name: Install rsyslog
          ansible.builtin.package:
            name: rsyslog
            state: present

        - name: Start rsyslog
          ansible.builtin.service:
            name: rsyslog
            state: started

    - name: Install dnspython on Debian/Ubuntu
      ansible.builtin.apt:
        name: python3-dnspython
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install dnspython on RHEL/Alma/Rocky/OL
      ansible.builtin.dnf:
        name: python3-dns
        state: present
      when: ansible_os_family == 'RedHat'
