---
# the sleep in the restart pdns-recursor handler
# is needed to make sure the service has been
# correctly stopped before being started again during restarts

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: not pdns_rec_disable_handlers

- name: restart pdns-recursor
  ansible.builtin.systemd:
    name: "{{ pdns_rec_service_name }}"
    state: restarted
  when: pdns_rec_service_state != 'stopped' and not pdns_rec_disable_handlers

- name: update the apt cache
  ansible.builtin.apt:
    update_cache: true
