---
# the sleep in the restart pdns-recursor handler
# is needed to make sure the service has been
# correctly stopped before being started again during restarts

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
  when: not pdns_rec_disable_handlers

- name: Restart pdns-recursor
  ansible.builtin.systemd:
    name: "{{ pdns_rec_service_name }}"
    state: restarted
  listen: restart pdns-recursor
  when: pdns_rec_service_state != 'stopped' and not pdns_rec_disable_handlers

- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: true
  listen: update the apt cache
