---

- name: Restart PowerDNS Recursor
  service:
    name: "{{ pdns_rec_service_name }}"
    state: restarted

- name: Reload systemd and restart PowerDNS Recursor
  command: systemctl daemon-reload
  notify: Restart PowerDNS Recursor
