---

##
# PowerDNS Recursor 5.2.x Repository
##

pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_52 }}"

pdns_rec_service_overrides:
  LimitCORE: infinity
  ExecStart: /usr/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog --log-timestamp=no
