---

##
# PowerDNS Recursor Configuration
##

pdns_rec_config:
  recursor:
    include_dir: "{{ pdns_rec_config_dir }}/recursor.d"
    threads: 2
    max_mthreads: 1024
    extended_resolution_errors: true
    forward_zones:
      - zone: example-forward.com
        forwarders:
          - 127.0.0.1:5301
    rpzs:
      - name: /var/lib/pdns-recursor/rpz/test2.rpz
      - name: test.rpz
        addresses: ["127.0.0.2"]

  incoming:
    reuseport: true
    allow_from: [ 127.0.0.0/8 ]

  webservice:
    address: 127.0.0.1
    port: 8001
    api_key: powerdns
    api_dir: "/var/lib/pdns-recursor/api"

pdns_rec_config_additional_dirs:
  - path: "{{ pdns_rec_config.webservice.api_dir }}"
    mode: '0775'
  - "{{ pdns_rec_config.recursor.include_dir }}"
  - "/var/lib/pdns-recursor/rpz"

pdns_rec_config_additional_files:
  - dest: "/var/lib/pdns-recursor/rpz/test2.rpz"
    content: |
      test2.rpz.               60   IN SOA    ns.test2.rpz. hostmaster.test2.rpz. 1 10800 60 3600 3600
      test-rpz.com.test2.rpz.  60   IN A  127.0.0.2

# Override service
pdns_rec_service_overrides:
  Unit:
    Description: PowerDNS Recursor (modified)
  Service:
    LimitCORE: infinity
    ExecStart: /usr/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog --log-timestamp=no
    Environment:
      TEST_VAR1: TEST_VALUE1
      TEST_VAR2: TEST_VALUE2
