---

scenario:
  name: pdns-rec-52

driver:
  name: docker

dependency:
  name: galaxy

platforms:

  - name: ubuntu-2204
    image: ubuntu:22.04
    dockerfile_tpl: debian-systemd

  - name: ubuntu-2404
    image: ubuntu:24.04
    dockerfile_tpl: debian-systemd

  - name: debian-11
    image: debian:11
    dockerfile_tpl: debian-systemd

  - name: debian-12
    image: debian:12
    dockerfile_tpl: debian-systemd

  - name: oraclelinux-8
    image: oraclelinux:8
    dockerfile_tpl: rhel-systemd

  - name: oraclelinux-9
    image: oraclelinux:9
    dockerfile_tpl: rhel-systemd

  - name: rockylinux-8
    image: rockylinux:8
    dockerfile_tpl: rhel-systemd

  - name: rockylinux-9
    image: rockylinux:9
    dockerfile_tpl: rhel-systemd

  - name: almalinux-8
    image: almalinux:8
    dockerfile_tpl: rhel-systemd

  - name: almalinux-9
    image: almalinux:9
    dockerfile_tpl: rhel-systemd

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  config_options:
    defaults:
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: .ansible_cache
      fact_caching_timeout: 7200
      vault_password_file: ${MOLECULE_SCENARIO_DIRECTORY}/../resources/.vault-password
    ssh_connection:
      pipelining: true
  inventory:
    links:
      host_vars: ../resources/host_vars/
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml
  lint: ansible-lint -x ANSIBLE0006 ANSIBLE0016

lint: yamllint vars tasks defaults meta

verifier:
  name: testinfra
  options:
    vvv: True
  directory: ../resources/tests/all
  additional_files_or_dirs:
    - ../repo-52/
    - ../systemd-overrides
