---

scenario:
  name: pdns-rec-master

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: centos-6
    image: centos:6

  - name: centos-7
    image: centos:7
    dockerfile_tpl: centos-systemd

  - name: centos-8
    image: centos:8
    dockerfile_tpl: centos-systemd

  - name: ubuntu-1804
    image: ubuntu:18.04

  - name: debian-9
    image: debian:9

  - name: debian-10
    image: debian:10

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml
  lint:
    name: ansible-lint
    options:
      x:
        # "systemctl used in place of systemd module"
        - "ANSIBLE0006"
        # "Tasks that run when changed should likely be handlers"
        - "ANSIBLE0016"

lint:
  name: yamllint

verifier:
  name: testinfra
  options:
    vvv: True
  directory: ../resources/tests/all
  additional_files_or_dirs:
    # path relative to '../resources/tests/all'
    - ../repo-master/
  lint:
    name: flake8
